# Generated by Django 4.1.1 on 2022-09-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_laptops_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='laptop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ownedBy', to='user.laptops'),
        ),
    ]
